name: CI
on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> "${GITHUB_PATH}"
    - name: Report versions
      run: |
        mdbook --version
    - name: Run tests
      run: mdbook test
  lint:
    name: Run lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> "${GITHUB_PATH}"
    - name: Report versions
      run: |
        mdbook --version
    - name: Lint for local file paths
      run: |
        mdbook build
    - name: Check for broken links
      run: |
        curl -sSLo linkcheck.sh \
          https://raw.githubusercontent.com/rust-lang/rust/master/src/tools/linkchecker/linkcheck.sh
        # Cannot use --all here because of the generated redirect pages aren't available.
        sh linkcheck.sh book
